version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-1"
    CLUSTER_NAME: "Sun-Series-Travel-Prod"
    K8S_NAMESPACE: "default"
    APP_NAME: "ms-access-control-1"
    PLACEHOLDER_IMAGE: "public.ecr.aws/docker/library/nginx:alpine"  # ภาพทดสอบ

phases:
  install:
    runtime-versions:
      java: corretto17   # จะไม่ใช้จริง แต่คงไว้ได้
    commands:
      - "set -euo pipefail"
      - "aws --version"
      - 'echo "Installing kubectl (fallback to dl.k8s.io)..."'
      - 'K8S_VER=$(aws eks describe-cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" --query "cluster.version" --output text)'
      - 'echo "Detected cluster.version: ${K8S_VER}"'
      - 'KUBE_URL_UP="https://dl.k8s.io/release/v${K8S_VER}.0/bin/linux/amd64/kubectl"'
      - 'curl -fsSL -o /usr/local/bin/kubectl "${KUBE_URL_UP}"'
      - 'chmod +x /usr/local/bin/kubectl'
      - 'kubectl version --client --output=yaml || (echo "kubectl not working"; exit 1)'

  pre_build:
    commands:
      - 'echo "Preparing smoke manifest..."'
      # สร้างไฟล์แมนิเฟสต์ชั่วคราว (Deployment + Service LoadBalancer)
      - |
        cat > /tmp/smoke.yaml <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${APP_NAME}-smoke
          labels: { app: ${APP_NAME}-smoke }
        spec:
          replicas: 2
          selector: { matchLabels: { app: ${APP_NAME}-smoke } }
          template:
            metadata: { labels: { app: ${APP_NAME}-smoke } }
            spec:
              containers:
                - name: nginx
                  image: ${PLACEHOLDER_IMAGE}
                  ports: [{ containerPort: 80 }]
                  readinessProbe:
                    httpGet: { path: /, port: 80 }
                    initialDelaySeconds: 5
                    periodSeconds: 5
                  livenessProbe:
                    httpGet: { path: /, port: 80 }
                    initialDelaySeconds: 15
                    periodSeconds: 10
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: ${APP_NAME}-smoke
          labels: { app: ${APP_NAME}-smoke }
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        spec:
          type: LoadBalancer
          selector: { app: ${APP_NAME}-smoke }
          ports:
            - port: 80
              targetPort: 80
              protocol: TCP
        EOF

  build:
    commands:
      - 'echo "Skip build (smoke deploy mode)"'

  post_build:
    commands:
      - 'echo "Updating kubeconfig..."'
      - 'aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"'
      - 'echo "Applying smoke manifest..."'
      - 'kubectl -n "$K8S_NAMESPACE" apply -f /tmp/smoke.yaml'
      - 'kubectl -n "$K8S_NAMESPACE" rollout status deploy/${APP_NAME}-smoke'
      - 'echo "Service details:"'
      - 'kubectl -n "$K8S_NAMESPACE" get svc ${APP_NAME}-smoke -o wide'
      - 'echo "Smoke deploy completed."'

artifacts:
  files:
    - "**/*"
